name = "Nanobyte"
license = "MIT"
licenselink = "https://opensource.org/licenses/MIT"
description = "The Nanobyte site theme"
homepage = "https://nanobyte.dev"
tags = ["blog", "technical", "os-development"]
features = ["responsive", "custom-fonts"]
min_version = "0.112.0"

[author]
  name = "Tiberiu Chibici"
  homepage = "https://nanobyte.dev"
